language: ruby
bundler_args: --without development
before_script:
  - sudo apt-get install aspell libaspell-dev aspell-pl
  - psql -c 'create database otwartezabytki_test;' -U postgres
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:schema:load
script:
  - bundle exec rspec spec
  - bundle exec cucumber
before_install:
  - sudo /usr/share/elasticsearch/bin/plugin -install chytreg/elasticsearch-analysis-morfologik/1.0.0
  - sudo service elasticsearch start
rvm:
  - 1.9.2
  - 1.9.3
branches:
  only:
    - dev
    - master

notifications:
  email:
    - dariusz.gertych@monterail.com
