development:
  adapter: postgresql
  encoding: unicode
  database: otwartezabytki_development
  username: otwartezabytki
  password:
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: otwartezabytki_test
  username: postgres
  password:
  pool: 5
  timeout: 5000
  port: 5432
  host: localhost
  template: template0
