debug_assets: true
secret_token: fallback_token_for_development
raven_dsn: fallback_dsn_for_development
oz:
  gm_key: 'AIzaSyCIvKKcWv1L2FrfLe5rNpnsah5OXm6gJMA'
  ga_key: 'Your Google Analytics key'
  email_sender: kontakt-oz@centrumcyfrowe.pl
  host: otwartezabytki.dev
  index_env: development
  locale:
    available:
      - :by
      - :de
      - :en
      - :fr
      - :lt
      - :pl
      - :ru
      - :se
      - :ua
    enabled:
      - :de
      - :en
      - :pl
  facebook:
    api_id: "179800448818038"
    api_secret: "1e6336767d27ed394094a740dc836996"
