debug_assets: true
oz:
  gm_key: 'Your Google Maps key'
  ga_key: 'Your Google Analytics key'
  email_sender: kontakt-oz@centrumcyfrowe.pl
  host: otwartezabytki.dev
  index_env: development
  facebook:
    api_id: "179800448818038"
    api_secret: "1e6336767d27ed394094a740dc836996"
